format = """
[\ue0b6](#9A348E)\
$time\
[\ue0b0](bg:#DA627D fg:#9A348E)\
$directory\
[\ue0b0](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[\ue0b0](fg:#FCA17D bg:#06969A)\
$c\
$golang\
$python\
$nodejs\
$rust\
[\ue0b0](fg:#06969A bg:#33658A)\
[\ue0b0 ](fg:#33658A)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like \uf120 to save some space
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "\uf718 "
"Downloads" = "\uf019 "
"Music" = "\uf001 "
"Pictures" = "\uf03e "
# Keep in mind that the order matters. For example:
# "Important Documents" = " \uf718\uf12a "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important \uf718 " = " \uf718\uf12a "

[c]
symbol = "\ue61e"
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "\uf418"
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "\ue627"
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "\ue73c"
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "\ue718"
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "\ue7a8"
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%H:%M:%S"
style = "bg:#9A348E"
format = '[♥ $time ]($style)'
